# Generated by Django 2.2.7 on 2020-01-12 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
